---

- name: install locales
  apt: name=locales state=present update_cache=yes cache_valid_time=1800

- name: generate locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - de_CH.UTF-8

- name: install locale configuration
  copy: src=etc_default_locale dest=/etc/default/locale owner=root group=root mode=0644

- meta: flush_handlers
