---
- name: install locales
  become: True
  apt: 
    name: locales
    state: present 
    update_cache: yes 
    cache_valid_time: 1800
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: generate locales
  become: True
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ regional_locales_installed }}"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- set_fact:
    locale_conf_path: /etc/default/locale
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- set_fact:
    locale_conf_path: /etc/locale.conf
  when: ansible_distribution == "Fedora"

- name: install locale configuration
  become: True
  template:
    src: etc_default_locale.j2
    dest: "{{ locale_conf_path }}"
    owner: root
    group: root
    mode: 0644

- meta: flush_handlers
